export const SUBMIT_INPUTS_SUCCESS = "SUBMIT_INPUTS_SUCCESS";
export const SUBMIT_INPUTS_FAIL = "SUBMIT_INPUTS_FAIL";
export const SUBMIT_INPUTS_START = "SUBMIT_INPUTS_START";
export const REBUILD_NODES_FROM_LOCAL_STORAGE =
  "nodes[rebuild_nodes_from_local_storage]";
export const SUBMIT_PATH_INPUTS_SUCCESS = "SUBMIT_PATH_INPUTS_SUCCESS";
export const SUBMIT_PATH_INPUTS_FAIL = "SUBMIT_PATH_INPUTS_FAIL";
export const SUBMIT_PATH_INPUTS_START = "SUBMIT_PATH_INPUTS_START";
export const REBUILD_PATHS_FROM_LOCAL_STORAGE =
  "REBUILD_PATHS_FROM_LOCAL_STORAGE";
export const MERGE_NODES_FOR_PATHS = "MERGE_NODES_FOR_PATHS";
export const REMOVE_NODE = "REMOVE_NODE";
export const REMOVE_PATH = "REMOVE_PATH";
export const START_LOGIN = "[auth] start login";
export const LOGIN_SUCCESS = "[auth] success login";
export const LOGIN_FAILED = "[auth] failed login";
export const SUBMIT_TRUCK_INPUTS_SUCCESS = "SUBMIT_TRUCK_INPUTS_SUCCESS";
export const SUBMIT_TRUCK_INPUTS_FAIL = "SUBMIT_TRUCK_INPUTS_FAIL";
export const SUBMIT_TRUCK_INPUTS_START = "SUBMIT_TRUCK_INPUTS_START";
export const REBUILD_TRUCKS_FROM_LOCAL_STORAGE =
  "TRUCKS[rebuild_trucks_from_local_storage]";
export const REMOVE_TRUCK = "REMOVE_TRUCK";
export const SUBMIT_DYNAMIC_TRUCK_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_TRUCK_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_TRUCK_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_TRUCK_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_TRUCK_INPUTS_START =
  "SUBMIT_DYNAMIC_TRUCK_INPUTS_START";
export const REBUILD_DYNAMIC_TRUCKS_FROM_LOCAL_STORAGE =
  "dynamicTrucks[REBUILD_DYNAMIC_TRUCKS_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_TRUCK = "REMOVE_DYNAMIC_TRUCK";
export const SUBMIT_DYNAMIC_NODE_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_NODE_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_NODE_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_NODE_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_NODE_INPUTS_START =
  "SUBMIT_DYNAMIC_NODE_INPUTS_START";
export const REBUILD_DYNAMIC_NODES_FROM_LOCAL_STORAGE =
  "dynamicNodes[REBUILD_DYNAMIC_NODES_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_NODE = "REMOVE_DYNAMIC_NODE";
export const SUBMIT_DYNAMIC_PATH_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_PATH_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_PATH_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_PATH_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_PATH_INPUTS_START =
  "SUBMIT_DYNAMIC_PATH_INPUTS_START";
export const REBUILD_DYNAMIC_PATHS_FROM_LOCAL_STORAGE =
  "dynamicPaths[REBUILD_DYNAMIC_PATHS_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_PATH = "REMOVE_DYNAMIC_PATH";
export const SUBMIT_DYNAMIC_PATH_COSTS_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_PATH_COSTS_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_PATH_COSTS_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_PATH_COSTS_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_PATH_COSTS_INPUTS_START =
  "SUBMIT_DYNAMIC_PATH_COSTS_INPUTS_START";
export const REBUILD_DYNAMIC_PATH_COSTS_FROM_LOCAL_STORAGE =
  "dynamicPaths[REBUILD_DYNAMIC_PATH_COSTS_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_PATH_COST = "REMOVE_DYNAMIC_PATH_COST";
export const SUBMIT_DYNAMIC_SHOWEL_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_SHOWEL_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_SHOWEL_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_SHOWEL_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_SHOWEL_INPUTS_START =
  "SUBMIT_DYNAMIC_SHOWEL_INPUTS_START";
export const REBUILD_DYNAMIC_SHOWELS_FROM_LOCAL_STORAGE =
  "dynamicPaths[REBUILD_DYNAMIC_SHOWELS_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_SHOWEL = "REMOVE_DYNAMIC_SHOWEL";
export const SUBMIT_DYNAMIC_CRUSHER_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_CRUSHER_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_CRUSHER_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_CRUSHER_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_CRUSHER_INPUTS_START =
  "SUBMIT_DYNAMIC_CRUSHER_INPUTS_START";
export const REBUILD_DYNAMIC_CRUSHERS_FROM_LOCAL_STORAGE =
  "dynamicPaths[REBUILD_DYNAMIC_CRUSHERS_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_CRUSHER = "REMOVE_DYNAMIC_CRUSHER";
export const SUBMIT_DYNAMIC_OREDEPOT_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_OREDEPOT_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_OREDEPOT_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_OREDEPOT_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_OREDEPOT_INPUTS_START =
  "SUBMIT_DYNAMIC_OREDEPOT_INPUTS_START";
export const REBUILD_DYNAMIC_OREDEPOTS_FROM_LOCAL_STORAGE =
  "dynamicPaths[REBUILD_DYNAMIC_OREDEPOTS_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_OREDEPOT = "REMOVE_DYNAMIC_OREDEPOT";
export const SUBMIT_DYNAMIC_DISCHARGE_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_DISCHARGE_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_DISCHARGE_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_DISCHARGE_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_DISCHARGE_INPUTS_START =
  "SUBMIT_DYNAMIC_DISCHARGE_INPUTS_START";
export const REBUILD_DYNAMIC_DISCHARGES_FROM_LOCAL_STORAGE =
  "dynamicPaths[REBUILD_DYNAMIC_DISCHARGES_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_DISCHARGE = "REMOVE_DYNAMIC_DISCHARGE";
export const SUBMIT_DYNAMIC_FINAL_INPUTS_SUCCESS =
  "SUBMIT_DYNAMIC_FINAL_INPUTS_SUCCESS";
export const SUBMIT_DYNAMIC_FINAL_INPUTS_FAIL =
  "SUBMIT_DYNAMIC_FINAL_INPUTS_FAIL";
export const SUBMIT_DYNAMIC_FINAL_INPUTS_START =
  "SUBMIT_DYNAMIC_FINAL_INPUTS_START";
export const REBUILD_DYNAMIC_FINALS_FROM_LOCAL_STORAGE =
  "dynamicPaths[REBUILD_DYNAMIC_FINALS_FROM_LOCAL_STORAGE]";
export const REMOVE_DYNAMIC_FINAL = "REMOVE_DYNAMIC_FINAL";

export const SUBMIT_GP_NODE_INPUTS_SUCCESS =
  "SUBMIT_GP_NODE_INPUTS_SUCCESS";
export const SUBMIT_GP_NODE_INPUTS_FAIL =
  "SUBMIT_GP_NODE_INPUTS_FAIL";
export const SUBMIT_GP_NODE_INPUTS_START =
  "SUBMIT_GP_NODE_INPUTS_START";
export const REBUILD_GP_NODES_FROM_LOCAL_STORAGE =
  "dynamicNodes[REBUILD_GP_NODES_FROM_LOCAL_STORAGE]";
export const REMOVE_GP_NODE = "REMOVE_GP_NODE";
